Repository FilipParyz/UE_Kat, pull requests merged in 2024-01, with the labels that each got.

#14 Saper
  Saper.py
Labels: enhancement

#15 Update user authentication logic
  Snake.py
Labels: bug, enhancement

#16 Merged additional games into main.
  main.py
Labels: enhancement

#17 Fixes to merge Snake into main
  main.py
Labels: bug

#18 Fixed window not focusing
  main.py
Labels: bug

#19 Poprawianie main
  Snake.py
  leaderboard.txt
Labels: game
